#version 460

layout(binding = 0, rgba32f) uniform readonly image2D linearTex;
layout(binding = 1, rgba8) uniform writeonly image2D outTex;

vec3 gamma_correct(vec3 color) {
    return pow(color, vec3(1.5));
}

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
void main() {

    ivec2 position = ivec2(gl_GlobalInvocationID.xy);

    vec3 color = imageLoad(linearTex, position).xyz;
    color = gamma_correct(color);
    imageStore(outTex, position, vec4(color, 1.0));
}